import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from "./NavBar";
import "@radix-ui/themes/styles.css";
import { Theme } from '@radix-ui/themes';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ResolveMe.app',
  description: 'Generated by ResolveMe',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <NavBar />
          <main>{children}</main>
        </Theme>
      </body>
    </html>
  );
}
